hostname: r2

interfaces:
  0/0:
    alias: connection to r1
    address: 172.16.0.2
    netmask: 255.255.255.0

  0/1:
    alias: connection to r3 
    address: 172.20.0.1
    netmask: 255.255.255.0

ospf:
  id: 1
  router_id: 10.10.10.2
  networks:
    - {network: 172.16.0.0, netmask: 0.0.0.255, area: 0}
    - {network: 172.20.0.0, netmask: 0.0.0.255, area: 1}
