hostname: r3

interfaces:
  0/0:
    alias: connection to r2 
    address: 172.20.0.2
    netmask: 255.255.255.0
  
  0/1:
    alias: local network
    address: 90.10.0.1 
    netmask: 255.255.255.0

ospf:
  id: 1
  router_id: 10.10.10.3
  networks:
    - {network: 172.20.0.0, netmask: 0.0.0.255, area: 1}
    - {network: 90.10.0.0, netmask: 0.0.0.255, area: 1}
